# Generated by Django 3.1.2 on 2020-10-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
